# Generated by Django 5.1.6 on 2025-05-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0006_alter_quizattempt_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_txt', models.CharField(blank=True, max_length=255, null=True)),
                ('questions_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('answers_txt', models.CharField(blank=True, max_length=255, null=True)),
                ('answers_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('user_attempt_txt', models.CharField(blank=True, max_length=255, null=True)),
                ('user_attempt_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('report_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download', to='quiz.quizattempt')),
            ],
        ),
    ]
