# Generated by Django 5.1.6 on 2025-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdownload',
            name='storage_index',
            field=models.IntegerField(default=0, help_text='Index of the file in storage'),
        ),
    ]
