# Generated by Django 5.1.6 on 2025-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quizattempt_score'),
        ('quiz_downloads', '0002_quizdownload_storage_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizdownload',
            index=models.Index(fields=['quiz_attempt'], name='quiz_downlo_quiz_at_8da862_idx'),
        ),
    ]
